name: Check project code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  php-cs-sniffer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xmlwriter, zip
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP CodeSniffer
        run: |
          ./vendor/bin/phpcs
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Все отлично, стиль кода соответствует правилам!"
            exit 0
          else
            echo "Произошла критическая ошибка выполнения CodeSniffer (код $EXIT_CODE)!"
            exit $EXIT_CODE
          fi
          
  php-unit-tests:
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: xmlwriter, zip, mbstring
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
